### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by waltari** [ppfeufer/eve-online-tranquility-status#1]
With recent wordpress update the widget stoped working for me (no idea whether just for me or anyone else too). All i can see in the shortcode area is the shortcode name [eve-tq-status]

https://www.capsuleer.cz/

**Comment by ppfeufer** [comment]
https://wpdev.ppfeufer.de/tq-status-short-code-test/

As you can see, it still works.

How do you have that one implemented?

**Comment by waltari** [comment]
Via custom HTML and shotcode widget to change color of the text to green. It worked fine untill recently.

`<p style="padding-top:-20px;margin-top:-5px;"><strong>Tranquility server status:</strong><br />
<span style="color: #2ba828; font-weight: bold; font-stretch: condensed;">[eve-tq-status]</span></p>`

![image](https://user-images.githubusercontent.com/6461794/101515316-83831300-397e-11eb-8dcf-2c056e99439f.png)

**Comment by ppfeufer** [comment]
Well, even that works

![image](https://user-images.githubusercontent.com/2989985/101516002-3fdcd900-397f-11eb-86ae-3ca4b270099c.png)

Btw, thanks to the click jacking on your website, you earned a spot on my DNS block list.

**Comment by waltari** [comment]
Any idea if there are any existing conflict with any plugins? Iam using Elementor on mine, could it conflict somehow? Also what do you mean with click jacking?
